import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Topnav from '@/components/header/topnav'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Six One',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    
    <html lang="en">      
      <body className= {inter.className}>
        <header className='w-screen sm:w-4/5 mx-auto'>
          <Topnav />
        </header>

        <main className='sm:w-4/5 mx-auto'>
          {children}
        </main>

        <footer className='sm:w-4/5 mx-auto'>

        </footer>
        
      </body>
    </html>
  )
}
